---
repos:
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.3.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-toml
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
        entry: poetry run mypy
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
